### ISSUE TITLE
DeltaTime defaulting to InvalidTimeFrame when changing time.

### ISSUE THREAD

**Issue by jctorre8** [ser316asu/Pankow_SER316#31]
When you create a new recording and try to change the time, the delta time field gets set to InvalidTimeFrame which then when  you reload the application causes the following exception:

Exception in thread "main" java.lang.NumberFormatException: For input string: "Invalid Time Frame"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at net.sf.memoranda.SummaryManager.getPlanningTime(SummaryManager.java:44)
	at net.sf.memoranda.ui.SummaryPanel.refresh(SummaryPanel.java:147)
	at net.sf.memoranda.ui.SummaryPanel.<init>(SummaryPanel.java:119)
	at net.sf.memoranda.ui.WorkPanel.<init>(WorkPanel.java:77)
	at net.sf.memoranda.ui.AppFrame.<init>(AppFrame.java:89)
	at net.sf.memoranda.ui.App.<init>(App.java:94)
	at net.sf.memoranda.Start.main(Start.java:63)

Maybe the time selection dialog should be fixed so we evade this issue.

**Comment by jctorre8** [comment]
Fixed with the following comit:
[Link to commit](`https://github.com/ser316asu/Pankow_SER316/commit/2f812b8292f6ed44a51d15dff72f5e523d063a2c `)
